version: "3.3"
services:
  keycloak:
    image: jboss/keycloak:11.0.0
    container_name: usik-keycloak
    environment:
      - KEYCLOAK_USER=login
      - KEYCLOAK_PASSWORD=password
    command:
      - "-b 0.0.0.0"
      - "-Dkeycloak.import=/opt/jboss/keycloak/imports/realm-export.json"
      - "-Dkeycloak.profile.feature.upload_scripts=enabled"
    ports:
      - 8081:8080
    volumes:
      - ./imports:/opt/jboss/keycloak/imports
  back:
    build:
      context: .
    ports:
      - 8080:8080
    container_name: usik-backend
  front:
    build:
      context: ./angularclient/
    command: sh -c "ng serve --host 0.0.0.0 --port 4200"
    ports:
      - 4200:4200
    container_name: usik-frontend