version: "3.3"
services:
  back:
    build:
      context: .
    ports:
      - 8080:8080
    container_name: usik-backend
  front:
    build:
      context: ./angularclient/
    ports:
      - 4200:80
    container_name: usik-frontend
  db:
    container_name: usik-database
    build: sql/
    ports:
      - 8081:8081
    command: java -cp ./lib/h2-1.4.200.jar org.h2.tools.RunScript -url jdbc:h2:mem:training -script insert.sql
